### ISSUE TITLE
Copying a message kills the app in 0.6.24

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#252]
Hi,

Thanks again for maintaining this app. When I try to copy a message in a conversation using the "copy icon" that shows up when long-pressing a message, the app dies.

I'm pretty sure this a regression with 0.6.24, as I used this in 0.6.23 without any problems, and now it happens systematically.

Here's a logcat dump of what happens. Hopefully it's helpful? Otherwise, I'm happy to debug and give you more info.

```
06-13 16:09:13.135 32135 32203 D ProfileInstaller: Skipping profile installation for net.kourlas.voipms_sms
06-13 16:09:13.942  1157 32075 I ActivityTaskManager: START u0 {cmp=net.kourlas.voipms_sms/.conversation.ConversationActivity (has extras)} from uid 10208
06-13 16:09:14.045  1157  1205 I ActivityTaskManager: Displayed net.kourlas.voipms_sms/.conversation.ConversationActivity: +102ms
06-13 16:09:17.951 32135 32135 E AndroidRuntime: Process: net.kourlas.voipms_sms, PID: 32135
06-13 16:09:17.951 32135 32135 E AndroidRuntime: 	at net.kourlas.voipms_sms.sms.Message.getMediaDisplayText(Message.kt:287)
06-13 16:09:17.951 32135 32135 E AndroidRuntime: 	at net.kourlas.voipms_sms.sms.Message.getFullDisplayText(Message.kt:269)
06-13 16:09:17.951 32135 32135 E AndroidRuntime: 	at net.kourlas.voipms_sms.conversation.ConversationActivity.onCopyButtonClick(ConversationActivity.kt:1186)
06-13 16:09:17.951 32135 32135 E AndroidRuntime: 	at net.kourlas.voipms_sms.conversation.ConversationActivity.onActionItemClicked(ConversationActivity.kt:1025)
06-13 16:09:17.954  1157 32075 W ActivityTaskManager:   Force finishing activity net.kourlas.voipms_sms/.conversation.ConversationActivity
06-13 16:09:18.004  1157 32075 I ActivityManager: Process net.kourlas.voipms_sms (pid 32135) has died: fg  TOP 
06-13 16:09:18.004  1157  2067 I WindowManager: WIN DEATH: Window{bba283c u0 net.kourlas.voipms_sms/net.kourlas.voipms_sms.conversations.ConversationsActivity}
06-13 16:09:18.004  1157  1813 D ConnectivityService: releasing NetworkRequest [ REQUEST id=487, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10208 RequestorUid: 10208 RequestorPkg: net.kourlas.voipms_sms] ] (release request)
06-13 16:09:18.004  1157  2067 W InputManager-JNI: Input channel object 'bba283c net.kourlas.voipms_sms/net.kourlas.voipms_sms.conversations.ConversationsActivity (client)' was disposed without first being removed with the input manager!
06-13 16:09:18.007  1157  2339 I WindowManager: WIN DEATH: Window{5d22e47 u0 net.kourlas.voipms_sms/net.kourlas.voipms_sms.conversation.ConversationActivity}
06-13 16:09:18.007  1157  2339 W InputManager-JNI: Input channel object '5d22e47 net.kourlas.voipms_sms/net.kourlas.voipms_sms.conversation.ConversationActivity (client)' was disposed without first being removed with the input manager!
06-13 16:09:18.013  1157  1213 W UsageStatsService: Unexpected activity event reported! (net.kourlas.voipms_sms/net.kourlas.voipms_sms.conversations.ConversationsActivity event : 23 instanceId : 56363662)
06-13 16:09:18.023  1157  1217 I ActivityManager: Start proc 32211:net.kourlas.voipms_sms/u0a208 for top-activity {net.kourlas.voipms_sms/net.kourlas.voipms_sms.conversations.ConversationsActivity}
06-13 16:09:18.111 32211 32211 V GraphicsEnvironment: ANGLE Developer option for 'net.kourlas.voipms_sms' set to: 'default'
06-13 16:09:18.112 32211 32211 V GraphicsEnvironment: ANGLE GameManagerService for net.kourlas.voipms_sms: false
06-13 16:09:18.278  1157 32075 D ConnectivityService: requestNetwork for uid/pid:10208/32211 activeRequest: null callbackRequest: 488 [NetworkRequest [ REQUEST id=489, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10208 RequestorUid: 10208 RequestorPkg: net.kourlas.voipms_sms] ]] callback flags: 0 priority: 2147483647
06-13 16:09:18.284  2148  2148 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ REQUEST id=489, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10208 RequestorUid: 10208 RequestorPkg: net.kourlas.voipms_sms] ]
06-13 16:09:18.285  1157  1792 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=489, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10208 RequestorUid: 10208 RequestorPkg: net.kourlas.voipms_sms] ]
06-13 16:09:18.286  1157  1792 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=489, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10208 RequestorUid: 10208 RequestorPkg: net.kourlas.voipms_sms] ]
06-13 16:09:18.286  1157  1792 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=489, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10208 RequestorUid: 10208 RequestorPkg: net.kourlas.voipms_sms] ]
06-13 16:09:18.467  1157  1208 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{2cd3e62 u0 net.kourlas.voipms_sms/.conversation.ConversationActivity t-1 f}}
06-13 16:09:18.681  1157  2067 W InputManager-JNI: Input channel object '800f372 Splash Screen net.kourlas.voipms_sms (client)' was disposed without first being removed with the input manager!
06-13 16:09:21.830 32211 32211 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=net.kourlas.voipms_sms/androidx.work.impl.foreground.SystemForegroundService (has extras) }
06-13 16:09:21.851 32211 32229 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=6158e601-f415-4228-8da3-a8fa93c7be4d, tags={ net.kourlas.voipms_sms.sms.workers.SyncWorker } ]
06-13 16:09:22.041  1157  1157 I NotificationService: Cannot find enqueued record for key: 0|net.kourlas.voipms_sms|1|null|10208
06-13 16:09:22.042  1157  1157 I NotificationService: Cannot find enqueued record for key: 0|net.kourlas.voipms_sms|1|null|10208
06-13 16:09:22.045  1157  1157 I NotificationService: Cannot find enqueued record for key: 0|net.kourlas.voipms_sms|1|null|10208
06-13 16:09:24.572 32211 32279 D ProfileInstaller: Skipping profile installation for net.kourlas.voipms_sms
```

**Comment by michaelkourlas** [comment]
Yep, this is a bug.

Thanks for finding it!
