### ISSUE TITLE
Crash when push notifications activated

### ISSUE THREAD

**Issue by adamzajdlik** [michaelkourlas/voipms-sms-client#89]
All crashed on launch after push notifications are enabled. Only occurs in version released today.

**Comment by michaelkourlas** [comment]
A number of people have reported this problem, though I can't reproduce it. They all have a stack trace similar to the following:

```
java.lang.RuntimeException: Unable to resume activity {net.kourlas.voipms_sms/net.kourlas.voipms_sms.activities.ConversationsActivity}: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9080000 but found 9683000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9080000 but found 9683000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
	at com.google.android.gms.common.zze.zzaj(Unknown Source)
	at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.zzc.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
	at net.kourlas.voipms_sms.notifications.PushNotifications.checkPlayServices(Unknown Source)
	at net.kourlas.voipms_sms.notifications.PushNotifications.registerForFcm(Unknown Source)
	at net.kourlas.voipms_sms.activities.ConversationsActivity.preRecentUpdate(Unknown Source)
	at net.kourlas.voipms_sms.activities.ConversationsActivity.onResume(Unknown Source)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
	at android.app.Activity.performResume(Activity.java:6327)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
	... 11 more
```

I've added `<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />` to the manifest, rebuilt from scratch, and released a new version to Google Play. It should be out in a few hours; hopefully that will fix the problem.

**Comment by michaelkourlas** [comment]
It looks like the people who are having this problem are running an out of date version of Google Play Services.

**Comment by michaelkourlas** [comment]
Okay, finally managed to reproduce and it looks like my fix works! :)
